server/clientapp/urls.py
from django.conf.urls import url
from clientapp import views as app_view
# from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', app_view.Home_view, name='home'),
    url(r'^raise-request/$', app_view.MakeRequest, name='makerequest'),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/icons/favicon.ico')),

]

server/splunk_handshake/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('clientapp.urls', namespace='clientapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/clientapp/models.py
from django.db import models

# Create your models here.

server/common_app/models.py
from django.db import models

# Create your models here.

server/clientapp/views.py
# Create your views here.

from django.conf import settings
from django.views import generic
from django.views.generic import View
from django.contrib.auth import authenticate, logout, get_user_model, login
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.http import Http404, HttpResponse, JsonResponse
from datetime import datetime, timedelta
from django.core.files.storage import default_storage

import os
import json

from django.core.mail import EmailMessage,send_mail
from clientapp.splunk_server_util import get_splunk_server_response

# Global declaration of operation folder
ROOT_FOLDER = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def Home_view(request):
    if request.method == 'POST':
        # return redirect('appserver:dashboard')
        # return render(request, 'home.html', {"user" : user})
        pass

    else:
        # GET, generate blank form
        return render(request, 'home.html', {"method": 'GET'})


def MakeRequest(request):
    if request.method == 'POST':
        try:
            # # POST, generate form with data from the request
            serverip = request.POST['serverip']
            username = request.POST['username']
            password = request.POST['passkey']
            keyword = request.POST['keyword']
            start_time_range = request.POST['eventday']
            email = request.POST['email']

            earliest_dt = ':'.join(start_time_range.split('   '))
            latest_dt = datetime.now().strftime("%m/%d/%Y:%H:%M:%S")

            print(serverip, username, password, keyword, email, earliest_dt, latest_dt)

            response_dict = get_splunk_server_response(serverip, username, password, keyword, earliest_dt, latest_dt)
            if response_dict['status']:
                mail_body_text = response_dict['searchqry_response']

                # email = EmailMessage('Test', 'Test', to=['sample_dev@gmail.com'])
                # email.send()

                # Send verification email
                send_mail(
                    'Splunk search results of query :' + keyword,
                    mail_body_text,
                    'msg2shanth@outlook.com',
                    [email],
                    fail_silently=False,
                )
                return render(request, 'home.html', {"method": 'POST', "status": "True", "eve_msg": "Search query responses sent to given Mail "})
            else:
                return render(request, 'home.html', {"method": 'POST', "status": "False", "eve_msg": "Problem in server, please check all fields. "})
        except Exception as e:
            print("Exception raise :", str(e))
            return render(request, 'home.html', {"method": 'POST', "status": "False", "eve_msg": "Problem in Processing, please check all fields. "})

    else:
        # GET, generate blank form
        return render(request, 'home.html')

server/common_app/views.py
from django.shortcuts import render

# Create your views here.

server/clientapp/templates/base.html
<!-- templates/base.html -->
{% load static %}

<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  	<link rel="icon" type="image/png"  href="{% static 'images/icons/favicon.ico' %}" />
  	<link rel="stylesheet" type="text/css"  href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animate/animate.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/css-hamburgers/hamburgers.min.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animsition/css/animsition.min.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/select2/select2.min.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/daterangepicker/daterangepicker.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/util.css' %}" />
  	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}" />
  <!--===============================================================================================-->
  	<script src="{% static 'assets/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'assets/vendor/animsition/js/animsition.min.js' %}"></script>
  	<script src="{% static 'assets/vendor/bootstrap/js/popper.js' %}"></script>
  	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  	<script src="{% static 'assets/vendor/select2/select2.min.js' %}"></script>
  	<script src="{% static 'assets/vendor/daterangepicker/moment.min.js' %}"></script>
  	<script src="{% static 'assets/vendor/daterangepicker/daterangepicker.js' %}"></script>
  	<script src="{% static 'assets/vendor/countdowntime/countdowntime.js' %}"></script>


  {% block jqueryscript %}{% endblock %}

  <title>{% block title %} {% endblock %}</title>
</head>

<body class="{% block body_class %} {% endblock body_class %}">

    {% block content %}
    {% endblock %}

</body>

{% block endjqueryscript %}{% endblock %}

</html>

server/clientapp/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Splunk Handshake{% endblock %}

{% block body_class %}{% endblock body_class %}

{% block content %}

<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
      <div class="login100-form-title" style="background-image: url({% static 'images/bg-01.jpg' %});">
      <!--	<span class="login100-form-title-1">
          Sign In
        </span> -->
      </div>

      <form class="login100-form validate-form" action="{% url 'clientapp:makerequest' %}" method="post" autocomplete="on">
        {% csrf_token %}
        <div class="wrap-input100 validate-input m-b-12" data-validate="Ip address is required">
          <span class="label-input100">Server </span>
          <input class="input100" type="text" name="serverip" placeholder="Enter Ip address">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-12" data-validate="Username is required">
          <span class="label-input100">Username</span>
          <input class="input100" type="text" name="username" placeholder="Enter username">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
          <span class="label-input100">Password</span>
          <input class="input100" type="password" name="passkey" placeholder="Enter password">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-12" data-validate="Queryword is required">
          <span class="label-input100">Keyword</span>
          <input class="input100" type="text" name="keyword" placeholder="Enter a search query">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-12 date form_datetime" data-validate="Time range is required">
          <span class="label-input100">Time_range (earliest) </span>
        <!--	<input class="input100" type="text" name="username" placeholder="Enter time range"> -->
          <!-- <input class="input100" type="date" id="eventday" name="eventday"> -->
          <input class="input100" type="text" id="eventday" name="eventday" readonly>
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-12" data-validate="Email is required">
          <span class="label-input100">Email</span>
          <input class="input100" type="email" name="email" placeholder="Enter the Email">
          <span class="focus-input100"></span>
        </div>
      <!--	<div class="flex-sb-m w-full p-b-30">
          <div class="contact100-form-checkbox">
            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
            <label class="label-checkbox100" for="ckb1">
              Remember me
            </label>
          </div>

          <div>
            <a href="#" class="txt1">
              Forgot Password?
            </a>
          </div>
        </div>  -->

        <div class="container-login100-form-btn">
          <input type="submit" class="login100-form-btn" value="Process">
        </div>

        {% if method == 'POST' %}
          <div class="input100 m-b-18">
              <h5 class="text-danger"> {{eve_msg}}</h5>
          </div>
        {% endif %}


      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block endjqueryscript %}
<script src="{% static 'assets/js/main.js' %}"></script>
{% endblock %}

server/clientapp/templates/org_home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Splunk Handshake</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url(images/bg-01.jpg);">
				<!--	<span class="login100-form-title-1">
						Sign In
					</span> -->
				</div>

				<form class="login100-form validate-form">
					<div class="wrap-input100 validate-input m-b-12" data-validate="Ip address is required">
						<span class="label-input100">Server </span>
						<input class="input100" type="text" name="username" placeholder="Enter Ip address">
						<span class="focus-input100"></span>
					</div>				
				
					<div class="wrap-input100 validate-input m-b-12" data-validate="Username is required">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="Enter username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="pass" placeholder="Enter password">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-12" data-validate="Queryword is required">
						<span class="label-input100">Keyword</span>
						<input class="input100" type="text" name="keyword" placeholder="Enter a search query">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-12" data-validate="Time range is required">
						<span class="label-input100">Time range </span>
					<!--	<input class="input100" type="text" name="username" placeholder="Enter time range"> -->
						<input class="input100" type="date" id="eventday" name="eventday">
						<span class="focus-input100"></span>
					</div>				
				
					<div class="wrap-input100 validate-input m-b-12" data-validate="Email is required">
						<span class="label-input100">Email</span>
						<input class="input100" type="email" name="email" placeholder="Enter the Email">
						<span class="focus-input100"></span>
					</div>
				<!--	<div class="flex-sb-m w-full p-b-30">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>

						<div>
							<a href="#" class="txt1">
								Forgot Password?
							</a>
						</div>
					</div>  -->

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Process
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>